/*
 * generated by Xtext 2.28.0
 */
package fr.n7.simplepdl.txt.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PDLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProcessAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProcessKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cProcessElementsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cProcessElementsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cProcessElementsProcessElementParserRuleCall_4_2_0 = (RuleCall)cProcessElementsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cProcessElementsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cProcessElementsProcessElementParserRuleCall_4_3_1_0 = (RuleCall)cProcessElementsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Process returns Process:
		//    {Process}
		//    'Process'
		//    name=EString
		//    '{'
		//        ('processElements' '{' processElements+=ProcessElement ( "," processElements+=ProcessElement)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Process}
		//'Process'
		//name=EString
		//'{'
		//    ('processElements' '{' processElements+=ProcessElement ( "," processElements+=ProcessElement)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Process}
		public Action getProcessAction_0() { return cProcessAction_0; }
		
		//'Process'
		public Keyword getProcessKeyword_1() { return cProcessKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('processElements' '{' processElements+=ProcessElement ( "," processElements+=ProcessElement)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'processElements'
		public Keyword getProcessElementsKeyword_4_0() { return cProcessElementsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//processElements+=ProcessElement
		public Assignment getProcessElementsAssignment_4_2() { return cProcessElementsAssignment_4_2; }
		
		//ProcessElement
		public RuleCall getProcessElementsProcessElementParserRuleCall_4_2_0() { return cProcessElementsProcessElementParserRuleCall_4_2_0; }
		
		//( "," processElements+=ProcessElement)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//processElements+=ProcessElement
		public Assignment getProcessElementsAssignment_4_3_1() { return cProcessElementsAssignment_4_3_1; }
		
		//ProcessElement
		public RuleCall getProcessElementsProcessElementParserRuleCall_4_3_1_0() { return cProcessElementsProcessElementParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ProcessElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.ProcessElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cProcessElement_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWorkDefinitionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cWorkSequenceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cGuidanceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRessourceParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//ProcessElement returns ProcessElement:
		//    ProcessElement_Impl | WorkDefinition | WorkSequence | Guidance | Ressource;
		@Override public ParserRule getRule() { return rule; }
		
		//ProcessElement_Impl | WorkDefinition | WorkSequence | Guidance | Ressource
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ProcessElement_Impl
		public RuleCall getProcessElement_ImplParserRuleCall_0() { return cProcessElement_ImplParserRuleCall_0; }
		
		//WorkDefinition
		public RuleCall getWorkDefinitionParserRuleCall_1() { return cWorkDefinitionParserRuleCall_1; }
		
		//WorkSequence
		public RuleCall getWorkSequenceParserRuleCall_2() { return cWorkSequenceParserRuleCall_2; }
		
		//Guidance
		public RuleCall getGuidanceParserRuleCall_3() { return cGuidanceParserRuleCall_3; }
		
		//Ressource
		public RuleCall getRessourceParserRuleCall_4() { return cRessourceParserRuleCall_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ProcessElement_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.ProcessElement_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProcessElementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProcessElementKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ProcessElement_Impl returns ProcessElement:
		//    {ProcessElement}
		//    'ProcessElement'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{ProcessElement}
		//'ProcessElement'
		public Group getGroup() { return cGroup; }
		
		//{ProcessElement}
		public Action getProcessElementAction_0() { return cProcessElementAction_0; }
		
		//'ProcessElement'
		public Keyword getProcessElementKeyword_1() { return cProcessElementKeyword_1; }
	}
	public class WorkDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.WorkDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWorkDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cWorkDefinitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLinksToPredecessorsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cLinksToPredecessorsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cLinksToPredecessorsWorkSequenceCrossReference_4_2_0 = (CrossReference)cLinksToPredecessorsAssignment_4_2.eContents().get(0);
		private final RuleCall cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1 = (RuleCall)cLinksToPredecessorsWorkSequenceCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cLinksToPredecessorsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0 = (CrossReference)cLinksToPredecessorsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLinksToSuccessorsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLinksToSuccessorsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cLinksToSuccessorsWorkSequenceCrossReference_5_2_0 = (CrossReference)cLinksToSuccessorsAssignment_5_2.eContents().get(0);
		private final RuleCall cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1 = (RuleCall)cLinksToSuccessorsWorkSequenceCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLinksToSuccessorsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0 = (CrossReference)cLinksToSuccessorsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cUsefulRessourcesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cUsefulRessourcesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cUsefulRessourcesUsefulRessourceParserRuleCall_6_2_0 = (RuleCall)cUsefulRessourcesAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cUsefulRessourcesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cUsefulRessourcesUsefulRessourceParserRuleCall_6_3_1_0 = (RuleCall)cUsefulRessourcesAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//WorkDefinition returns WorkDefinition:
		//    {WorkDefinition}
		//    'WorkDefinition'
		//    name=EString
		//    '{'
		//        ('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] ( "," linksToPredecessors+=[WorkSequence|EString])* ')' )?
		//        ('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString] ( "," linksToSuccessors+=[WorkSequence|EString])* ')' )?
		//        ('usefulRessources' '{' usefulRessources+=UsefulRessource ( "," usefulRessources+=UsefulRessource)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{WorkDefinition}
		//'WorkDefinition'
		//name=EString
		//'{'
		//    ('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] ( "," linksToPredecessors+=[WorkSequence|EString])* ')' )?
		//    ('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString] ( "," linksToSuccessors+=[WorkSequence|EString])* ')' )?
		//    ('usefulRessources' '{' usefulRessources+=UsefulRessource ( "," usefulRessources+=UsefulRessource)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{WorkDefinition}
		public Action getWorkDefinitionAction_0() { return cWorkDefinitionAction_0; }
		
		//'WorkDefinition'
		public Keyword getWorkDefinitionKeyword_1() { return cWorkDefinitionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] ( "," linksToPredecessors+=[WorkSequence|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'linksToPredecessors'
		public Keyword getLinksToPredecessorsKeyword_4_0() { return cLinksToPredecessorsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//linksToPredecessors+=[WorkSequence|EString]
		public Assignment getLinksToPredecessorsAssignment_4_2() { return cLinksToPredecessorsAssignment_4_2; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToPredecessorsWorkSequenceCrossReference_4_2_0() { return cLinksToPredecessorsWorkSequenceCrossReference_4_2_0; }
		
		//EString
		public RuleCall getLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1() { return cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1; }
		
		//( "," linksToPredecessors+=[WorkSequence|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//linksToPredecessors+=[WorkSequence|EString]
		public Assignment getLinksToPredecessorsAssignment_4_3_1() { return cLinksToPredecessorsAssignment_4_3_1; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0() { return cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1() { return cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString] ( "," linksToSuccessors+=[WorkSequence|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'linksToSuccessors'
		public Keyword getLinksToSuccessorsKeyword_5_0() { return cLinksToSuccessorsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//linksToSuccessors+=[WorkSequence|EString]
		public Assignment getLinksToSuccessorsAssignment_5_2() { return cLinksToSuccessorsAssignment_5_2; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToSuccessorsWorkSequenceCrossReference_5_2_0() { return cLinksToSuccessorsWorkSequenceCrossReference_5_2_0; }
		
		//EString
		public RuleCall getLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1() { return cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1; }
		
		//( "," linksToSuccessors+=[WorkSequence|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//linksToSuccessors+=[WorkSequence|EString]
		public Assignment getLinksToSuccessorsAssignment_5_3_1() { return cLinksToSuccessorsAssignment_5_3_1; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0() { return cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1() { return cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('usefulRessources' '{' usefulRessources+=UsefulRessource ( "," usefulRessources+=UsefulRessource)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'usefulRessources'
		public Keyword getUsefulRessourcesKeyword_6_0() { return cUsefulRessourcesKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//usefulRessources+=UsefulRessource
		public Assignment getUsefulRessourcesAssignment_6_2() { return cUsefulRessourcesAssignment_6_2; }
		
		//UsefulRessource
		public RuleCall getUsefulRessourcesUsefulRessourceParserRuleCall_6_2_0() { return cUsefulRessourcesUsefulRessourceParserRuleCall_6_2_0; }
		
		//( "," usefulRessources+=UsefulRessource)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//usefulRessources+=UsefulRessource
		public Assignment getUsefulRessourcesAssignment_6_3_1() { return cUsefulRessourcesAssignment_6_3_1; }
		
		//UsefulRessource
		public RuleCall getUsefulRessourcesUsefulRessourceParserRuleCall_6_3_1_0() { return cUsefulRessourcesUsefulRessourceParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class WorkSequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.WorkSequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWorkSequenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLinkTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLinkTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLinkTypeWorkSequenceTypeEnumRuleCall_3_0 = (RuleCall)cLinkTypeAssignment_3.eContents().get(0);
		private final Keyword cPredecessorKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPredecessorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cPredecessorWorkDefinitionCrossReference_5_0 = (CrossReference)cPredecessorAssignment_5.eContents().get(0);
		private final RuleCall cPredecessorWorkDefinitionEStringParserRuleCall_5_0_1 = (RuleCall)cPredecessorWorkDefinitionCrossReference_5_0.eContents().get(1);
		private final Keyword cSuccessorKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSuccessorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cSuccessorWorkDefinitionCrossReference_7_0 = (CrossReference)cSuccessorAssignment_7.eContents().get(0);
		private final RuleCall cSuccessorWorkDefinitionEStringParserRuleCall_7_0_1 = (RuleCall)cSuccessorWorkDefinitionCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//WorkSequence returns WorkSequence:
		//    'WorkSequence'
		//    '{'
		//        'linkType' linkType=WorkSequenceType
		//        'predecessor' predecessor=[WorkDefinition|EString]
		//        'successor' successor=[WorkDefinition|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'WorkSequence'
		//'{'
		//    'linkType' linkType=WorkSequenceType
		//    'predecessor' predecessor=[WorkDefinition|EString]
		//    'successor' successor=[WorkDefinition|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'WorkSequence'
		public Keyword getWorkSequenceKeyword_0() { return cWorkSequenceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'linkType'
		public Keyword getLinkTypeKeyword_2() { return cLinkTypeKeyword_2; }
		
		//linkType=WorkSequenceType
		public Assignment getLinkTypeAssignment_3() { return cLinkTypeAssignment_3; }
		
		//WorkSequenceType
		public RuleCall getLinkTypeWorkSequenceTypeEnumRuleCall_3_0() { return cLinkTypeWorkSequenceTypeEnumRuleCall_3_0; }
		
		//'predecessor'
		public Keyword getPredecessorKeyword_4() { return cPredecessorKeyword_4; }
		
		//predecessor=[WorkDefinition|EString]
		public Assignment getPredecessorAssignment_5() { return cPredecessorAssignment_5; }
		
		//[WorkDefinition|EString]
		public CrossReference getPredecessorWorkDefinitionCrossReference_5_0() { return cPredecessorWorkDefinitionCrossReference_5_0; }
		
		//EString
		public RuleCall getPredecessorWorkDefinitionEStringParserRuleCall_5_0_1() { return cPredecessorWorkDefinitionEStringParserRuleCall_5_0_1; }
		
		//'successor'
		public Keyword getSuccessorKeyword_6() { return cSuccessorKeyword_6; }
		
		//successor=[WorkDefinition|EString]
		public Assignment getSuccessorAssignment_7() { return cSuccessorAssignment_7; }
		
		//[WorkDefinition|EString]
		public CrossReference getSuccessorWorkDefinitionCrossReference_7_0() { return cSuccessorWorkDefinitionCrossReference_7_0; }
		
		//EString
		public RuleCall getSuccessorWorkDefinitionEStringParserRuleCall_7_0_1() { return cSuccessorWorkDefinitionEStringParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class GuidanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.Guidance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGuidanceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGuidanceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTextKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTextAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_3_1_0 = (RuleCall)cTextAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cElementsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cElementsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cElementsProcessElementCrossReference_4_2_0 = (CrossReference)cElementsAssignment_4_2.eContents().get(0);
		private final RuleCall cElementsProcessElementEStringParserRuleCall_4_2_0_1 = (RuleCall)cElementsProcessElementCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cElementsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cElementsProcessElementCrossReference_4_3_1_0 = (CrossReference)cElementsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cElementsProcessElementEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cElementsProcessElementCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Guidance returns Guidance:
		//    {Guidance}
		//    'Guidance'
		//    '{'
		//        ('text' text=EString)?
		//        ('elements' '(' elements+=[ProcessElement|EString] ( "," elements+=[ProcessElement|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Guidance}
		//'Guidance'
		//'{'
		//    ('text' text=EString)?
		//    ('elements' '(' elements+=[ProcessElement|EString] ( "," elements+=[ProcessElement|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Guidance}
		public Action getGuidanceAction_0() { return cGuidanceAction_0; }
		
		//'Guidance'
		public Keyword getGuidanceKeyword_1() { return cGuidanceKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('text' text=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'text'
		public Keyword getTextKeyword_3_0() { return cTextKeyword_3_0; }
		
		//text=EString
		public Assignment getTextAssignment_3_1() { return cTextAssignment_3_1; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_3_1_0() { return cTextEStringParserRuleCall_3_1_0; }
		
		//('elements' '(' elements+=[ProcessElement|EString] ( "," elements+=[ProcessElement|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'elements'
		public Keyword getElementsKeyword_4_0() { return cElementsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//elements+=[ProcessElement|EString]
		public Assignment getElementsAssignment_4_2() { return cElementsAssignment_4_2; }
		
		//[ProcessElement|EString]
		public CrossReference getElementsProcessElementCrossReference_4_2_0() { return cElementsProcessElementCrossReference_4_2_0; }
		
		//EString
		public RuleCall getElementsProcessElementEStringParserRuleCall_4_2_0_1() { return cElementsProcessElementEStringParserRuleCall_4_2_0_1; }
		
		//( "," elements+=[ProcessElement|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//elements+=[ProcessElement|EString]
		public Assignment getElementsAssignment_4_3_1() { return cElementsAssignment_4_3_1; }
		
		//[ProcessElement|EString]
		public CrossReference getElementsProcessElementCrossReference_4_3_1_0() { return cElementsProcessElementCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getElementsProcessElementEStringParserRuleCall_4_3_1_0_1() { return cElementsProcessElementEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class RessourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.Ressource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRessourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuantityKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cQuantityAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cQuantityEIntParserRuleCall_4_0 = (RuleCall)cQuantityAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Ressource returns Ressource:
		//    'Ressource'
		//    name=EString
		//    '{'
		//        'quantity' quantity=EInt
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Ressource'
		//name=EString
		//'{'
		//    'quantity' quantity=EInt
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Ressource'
		public Keyword getRessourceKeyword_0() { return cRessourceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'quantity'
		public Keyword getQuantityKeyword_3() { return cQuantityKeyword_3; }
		
		//quantity=EInt
		public Assignment getQuantityAssignment_4() { return cQuantityAssignment_4; }
		
		//EInt
		public RuleCall getQuantityEIntParserRuleCall_4_0() { return cQuantityEIntParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class UsefulRessourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.UsefulRessource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUsefulRessourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUsefulQuantityKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUsefulQuantityAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUsefulQuantityEIntParserRuleCall_3_0 = (RuleCall)cUsefulQuantityAssignment_3.eContents().get(0);
		private final Keyword cRessourceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRessourceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cRessourceRessourceCrossReference_5_0 = (CrossReference)cRessourceAssignment_5.eContents().get(0);
		private final RuleCall cRessourceRessourceEStringParserRuleCall_5_0_1 = (RuleCall)cRessourceRessourceCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//UsefulRessource returns UsefulRessource:
		//    'UsefulRessource'
		//    '{'
		//        'usefulQuantity' usefulQuantity=EInt
		//        'ressource' ressource=[Ressource|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'UsefulRessource'
		//'{'
		//    'usefulQuantity' usefulQuantity=EInt
		//    'ressource' ressource=[Ressource|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'UsefulRessource'
		public Keyword getUsefulRessourceKeyword_0() { return cUsefulRessourceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'usefulQuantity'
		public Keyword getUsefulQuantityKeyword_2() { return cUsefulQuantityKeyword_2; }
		
		//usefulQuantity=EInt
		public Assignment getUsefulQuantityAssignment_3() { return cUsefulQuantityAssignment_3; }
		
		//EInt
		public RuleCall getUsefulQuantityEIntParserRuleCall_3_0() { return cUsefulQuantityEIntParserRuleCall_3_0; }
		
		//'ressource'
		public Keyword getRessourceKeyword_4() { return cRessourceKeyword_4; }
		
		//ressource=[Ressource|EString]
		public Assignment getRessourceAssignment_5() { return cRessourceAssignment_5; }
		
		//[Ressource|EString]
		public CrossReference getRessourceRessourceCrossReference_5_0() { return cRessourceRessourceCrossReference_5_0; }
		
		//EString
		public RuleCall getRessourceRessourceEStringParserRuleCall_5_0_1() { return cRessourceRessourceEStringParserRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class WorkSequenceTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.simplepdl.txt.PDL.WorkSequenceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStartToStartEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStartToStartStartToStartKeyword_0_0 = (Keyword)cStartToStartEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFinishToStartEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFinishToStartFinishToStartKeyword_1_0 = (Keyword)cFinishToStartEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStartToFinishEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStartToFinishStartToFinishKeyword_2_0 = (Keyword)cStartToFinishEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFinishToFinishEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFinishToFinishFinishToFinishKeyword_3_0 = (Keyword)cFinishToFinishEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum WorkSequenceType returns WorkSequenceType:
		//                startToStart = 'startToStart' | finishToStart = 'finishToStart' | startToFinish = 'startToFinish' | finishToFinish = 'finishToFinish';
		public EnumRule getRule() { return rule; }
		
		//startToStart = 'startToStart' | finishToStart = 'finishToStart' | startToFinish = 'startToFinish' | finishToFinish = 'finishToFinish'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//startToStart = 'startToStart'
		public EnumLiteralDeclaration getStartToStartEnumLiteralDeclaration_0() { return cStartToStartEnumLiteralDeclaration_0; }
		
		//'startToStart'
		public Keyword getStartToStartStartToStartKeyword_0_0() { return cStartToStartStartToStartKeyword_0_0; }
		
		//finishToStart = 'finishToStart'
		public EnumLiteralDeclaration getFinishToStartEnumLiteralDeclaration_1() { return cFinishToStartEnumLiteralDeclaration_1; }
		
		//'finishToStart'
		public Keyword getFinishToStartFinishToStartKeyword_1_0() { return cFinishToStartFinishToStartKeyword_1_0; }
		
		//startToFinish = 'startToFinish'
		public EnumLiteralDeclaration getStartToFinishEnumLiteralDeclaration_2() { return cStartToFinishEnumLiteralDeclaration_2; }
		
		//'startToFinish'
		public Keyword getStartToFinishStartToFinishKeyword_2_0() { return cStartToFinishStartToFinishKeyword_2_0; }
		
		//finishToFinish = 'finishToFinish'
		public EnumLiteralDeclaration getFinishToFinishEnumLiteralDeclaration_3() { return cFinishToFinishEnumLiteralDeclaration_3; }
		
		//'finishToFinish'
		public Keyword getFinishToFinishFinishToFinishKeyword_3_0() { return cFinishToFinishFinishToFinishKeyword_3_0; }
	}
	
	private final ProcessElements pProcess;
	private final ProcessElementElements pProcessElement;
	private final EStringElements pEString;
	private final ProcessElement_ImplElements pProcessElement_Impl;
	private final WorkDefinitionElements pWorkDefinition;
	private final WorkSequenceElements pWorkSequence;
	private final GuidanceElements pGuidance;
	private final RessourceElements pRessource;
	private final UsefulRessourceElements pUsefulRessource;
	private final EIntElements pEInt;
	private final WorkSequenceTypeElements eWorkSequenceType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProcess = new ProcessElements();
		this.pProcessElement = new ProcessElementElements();
		this.pEString = new EStringElements();
		this.pProcessElement_Impl = new ProcessElement_ImplElements();
		this.pWorkDefinition = new WorkDefinitionElements();
		this.pWorkSequence = new WorkSequenceElements();
		this.pGuidance = new GuidanceElements();
		this.pRessource = new RessourceElements();
		this.pUsefulRessource = new UsefulRessourceElements();
		this.pEInt = new EIntElements();
		this.eWorkSequenceType = new WorkSequenceTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.n7.simplepdl.txt.PDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Process returns Process:
	//    {Process}
	//    'Process'
	//    name=EString
	//    '{'
	//        ('processElements' '{' processElements+=ProcessElement ( "," processElements+=ProcessElement)* '}' )?
	//    '}';
	public ProcessElements getProcessAccess() {
		return pProcess;
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//ProcessElement returns ProcessElement:
	//    ProcessElement_Impl | WorkDefinition | WorkSequence | Guidance | Ressource;
	public ProcessElementElements getProcessElementAccess() {
		return pProcessElement;
	}
	
	public ParserRule getProcessElementRule() {
		return getProcessElementAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//ProcessElement_Impl returns ProcessElement:
	//    {ProcessElement}
	//    'ProcessElement'
	//    ;
	public ProcessElement_ImplElements getProcessElement_ImplAccess() {
		return pProcessElement_Impl;
	}
	
	public ParserRule getProcessElement_ImplRule() {
		return getProcessElement_ImplAccess().getRule();
	}
	
	//WorkDefinition returns WorkDefinition:
	//    {WorkDefinition}
	//    'WorkDefinition'
	//    name=EString
	//    '{'
	//        ('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] ( "," linksToPredecessors+=[WorkSequence|EString])* ')' )?
	//        ('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString] ( "," linksToSuccessors+=[WorkSequence|EString])* ')' )?
	//        ('usefulRessources' '{' usefulRessources+=UsefulRessource ( "," usefulRessources+=UsefulRessource)* '}' )?
	//    '}';
	public WorkDefinitionElements getWorkDefinitionAccess() {
		return pWorkDefinition;
	}
	
	public ParserRule getWorkDefinitionRule() {
		return getWorkDefinitionAccess().getRule();
	}
	
	//WorkSequence returns WorkSequence:
	//    'WorkSequence'
	//    '{'
	//        'linkType' linkType=WorkSequenceType
	//        'predecessor' predecessor=[WorkDefinition|EString]
	//        'successor' successor=[WorkDefinition|EString]
	//    '}';
	public WorkSequenceElements getWorkSequenceAccess() {
		return pWorkSequence;
	}
	
	public ParserRule getWorkSequenceRule() {
		return getWorkSequenceAccess().getRule();
	}
	
	//Guidance returns Guidance:
	//    {Guidance}
	//    'Guidance'
	//    '{'
	//        ('text' text=EString)?
	//        ('elements' '(' elements+=[ProcessElement|EString] ( "," elements+=[ProcessElement|EString])* ')' )?
	//    '}';
	public GuidanceElements getGuidanceAccess() {
		return pGuidance;
	}
	
	public ParserRule getGuidanceRule() {
		return getGuidanceAccess().getRule();
	}
	
	//Ressource returns Ressource:
	//    'Ressource'
	//    name=EString
	//    '{'
	//        'quantity' quantity=EInt
	//    '}';
	public RessourceElements getRessourceAccess() {
		return pRessource;
	}
	
	public ParserRule getRessourceRule() {
		return getRessourceAccess().getRule();
	}
	
	//UsefulRessource returns UsefulRessource:
	//    'UsefulRessource'
	//    '{'
	//        'usefulQuantity' usefulQuantity=EInt
	//        'ressource' ressource=[Ressource|EString]
	//    '}';
	public UsefulRessourceElements getUsefulRessourceAccess() {
		return pUsefulRessource;
	}
	
	public ParserRule getUsefulRessourceRule() {
		return getUsefulRessourceAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum WorkSequenceType returns WorkSequenceType:
	//                startToStart = 'startToStart' | finishToStart = 'finishToStart' | startToFinish = 'startToFinish' | finishToFinish = 'finishToFinish';
	public WorkSequenceTypeElements getWorkSequenceTypeAccess() {
		return eWorkSequenceType;
	}
	
	public EnumRule getWorkSequenceTypeRule() {
		return getWorkSequenceTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
